### PR TITLE
Fix: After killing phantom error (fixes #82 , fixes #78)

### LINKED ISSUE #78: Error when using PhantomJS.spawn() with grunt.util.async.forEachSeries() after update to 0.7.0
Hi, maybe I'm doing something wrong, but after updating ```grunt-lib-phantomjs``` to version 0.7.0, I'm getting following error:
```
PhantomJS threw an error:ERROR
>> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null. Use --force to continue.
```

I'm using PhantomJS.spawn() in grunt.util.async.forEachSeries() loop.
```js
grunt.util.async.forEachSeries(options.urls, function (url, next) {
    PhantomJS.spawn(host + url, {
        options: {
            phantomScript: phantomScript,
            timeout: options.timeout,
            cookies: options.cookies,
            page: options.page
        },
        done: function (error) {
            if (error) {
                done();
            } else {
                if (options.urls[options.urls.length - 1] === url.replace(host, '')) {
                    done();
                } else {
                    next();
                }
            }
        }
    });
});
```

Short debugging shows that issue was caused by this commit: 07bd6780b3f6a0d25fb2136c95ca6783bf739bcb

After changing this line ```phantomJSHandle.pid``` back to ```phantomJSHandle.connected``` everything works just as expected.

List of ```options.urls``` is huge, and process is failing each time in a different place.
Looks like PhantomJS is killed in the middle of processing list, and passing ```options.killTimeout``` with some big number (enough for processing the whole list) does not help.

### LINKED ISSUE #82: 0.7.0 version fails with an error
As of now `grunt-contrib-jasmine` and `grunt-contrib-qunit` both use this module but they are still using `0.6.0` version. Nobody is using `0.7.0`. I tried it on my machine to make `grunt-contrib-jasmine` use `0.7.0` version but it fails. I upgraded because i wanted to get https://github.com/gruntjs/grunt-contrib-jasmine/issues/167 issue fixed.

here is the error I get:

```sh
152 specs in 3.748s.
>> 0 failures

Done, without errors.
15:39:20 : Test run complete 

PhantomJS threw an error:ERROR
>> 0 [ '' ]
Warning: PhantomJS exited unexpectedly with exit code null.� Used --force, continuing.
>> 0 failures
fs.js:77
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
            ^
Error: ENOENT, unlink 'C:\Users\gs025879\AppData\Local\Temp\1435264754241.051'
    at Error (native)

Process finished with exit code 1
```

Nodejs: 0.12.5
OS: Windows 7

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

**Comment by gyandeeps** [comment]
@shama @sindresorhus @vladikoff Please review as this fix is needed for good.
Thanks

**Comment by gyandeeps** [comment]
CC @jzaefferer @cowboy @jsoverson

**Comment by gyandeeps** [comment]
@vladikoff Need your help here plz

**Comment by vladikoff** [comment]
@gyandeeps what help do you need?

**Comment by gyandeeps** [comment]
Feedback or if its good then a merge and release. 
So that jasmine and qunit can actually utilize this functionality. As right now both our at `^0.6.0` version which doesn't kill the phantom so everytime you run it spins off a new phatomjs.

**Comment by vladikoff** [comment]
Code null is a bit strange from spawn, but could be some node issue

**Comment by gyandeeps** [comment]
I had the same thought. 
Thanks for this and I will send a PR to update the version on grunt-contrib-jasmine for version update. As these changes were reverted because of this issue.

Thanks a lot.

**Comment by vladikoff** [comment]
@gyandeeps yeah no problem :smile: , I published 0.7.1 on npm

**Comment by gyandeeps** [comment]
Awesome. Thanks for help again. :+1:

**Pull request merged**
