### PR TITLE
[WIP] Use WebSockets for IPC instead of file I/O

### PR DESCRIPTION
**Pull request by Arkni**

### CODE REVIEW

**Comment by Arkni** [comment]
@vladikoff 
I think someone disabled `Travis CI` for this repo. Any thought on this ?

**Comment by Arkni** [comment]
Never mind, force pushed and it's working now :)

**Comment by Arkni** [comment]
This PR needs review!

**Comment by Arkni** [comment]
Could anyone, please, review this PR ?

**Comment by BYK** [comment]
@Arkni - hey, I'll try to review this week. Works for you?

**Comment by BYK** [comment]
I mean not sure if me reviewing it matters :D Still I can provide feedback.

**Comment by Arkni** [comment]
Sure! Any help is welcome :)
Thanks :)

**Comment by sindresorhus** [comment]
Closing as PhantomJS is deprecated.

**Pull request closed without merging**
